packages:
  - "packages/*"

catalog:
  "@jsonforms/core": "3.7.0"
  "@jsonforms/vue": "3.7.0"
  "@jsonforms/vue-vuetify": "3.7.0"
  "@chobantonov/jsonforms-vuetify-renderers": "3.7.0"
  "vue": "^3.5.0"
  "@vue/compiler-dom": "^3.5.0"
  "vuetify": "^3.11.0"
